alias c="cursor"
alias cd="z"
alias che="chezmoi"
alias ls="eza -a --icons=always --color=always"
alias ll="eza -a --icons=always --color=always -l"
alias stt="wezterm cli set-tab-title"
alias vi="nvim"
alias vim="nvim"
alias yolo="claude --dangerously-skip-permissions"
